# Generated by Django 3.0.14 on 2022-06-28 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class_in',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Student', 'Tutor'), ('Teacher', 'Tuition')], max_length=20, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('birth_date', models.DateField()),
                ('blood_group', models.CharField(choices=[('A+', 'A+ (A positive)'), ('A-', 'A- (A negative)'), ('B+', 'B+ (B positive)'), ('B-', 'B- (B negative)'), ('AB+', 'AB+ (AB positive)'), ('AB-', 'AB- (AB negative)'), ('O+', 'O+ (O positive)'), ('O-', 'O- (O negative)')], max_length=3)),
                ('nationality', models.CharField(choices=[('Bangladeshi', 'Bangladeshi'), ('Other', 'Other')], max_length=30)),
                ('religion', models.CharField(choices=[('Islam', 'Islam'), ('Hindu', 'Hinduism'), ('Buddhism', 'Buddhism'), ('Christianity', 'Chirstianity'), ('Other', 'Other')], max_length=20, null=True)),
                ('biodata', models.TextField()),
                ('phone', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=30, null=True)),
                ('image', models.ImageField(default='default.png', upload_to='session/images/')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Upazilla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upazilla', to='session.District')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TuitionProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=150)),
                ('style', multiselectfield.db.fields.MultiSelectField(choices=[('Group_Tuition', 'Group Tuition'), ('Private_Tuition', 'Private Tuition')], max_length=100)),
                ('place', multiselectfield.db.fields.MultiSelectField(choices=[('Class_Rooms', 'Class Rooms'), ('Coaching_Center', 'Coaching Center'), ('Home_Visit', 'Home Visit'), ('My_Place', 'My Place'), ('Online', 'Online')], max_length=100)),
                ('approach', multiselectfield.db.fields.MultiSelectField(choices=[('Online_Help', 'Online Help'), ('Phone_Help', 'Phone Help'), ('Provide_Hand_Notes', 'Provide Hand Notes'), ('Video_Tutorials', 'Video Tutorials')], max_length=100)),
                ('medium', multiselectfield.db.fields.MultiSelectField(choices=[('Arabic_Medium', 'Arabic'), ('Bangla_Medium', 'Bangla'), ('English_Medium', 'English')], max_length=100)),
                ('classes', multiselectfield.db.fields.MultiSelectField(choices=[('0', 'Pre-Primary'), ('1', 'Class 1'), ('2', 'Class 2'), ('3', 'Class 3'), ('4', 'Class 4'), ('5', 'Class 5'), ('6', 'Class 6'), ('7', 'Class 7'), ('8', 'Class 8'), ('9', 'Class 9'), ('10', 'Class 10'), ('11', 'College Student'), ('12', 'University Student'), ('13', 'Madrasha Student'), ('14', 'Technical Student'), ('15', 'Diploma Student')], max_length=150, null=True)),
                ('subjects', multiselectfield.db.fields.MultiSelectField(choices=[('0', 'Arabic'), ('1', 'Bangla'), ('3', 'English'), ('2', 'Math'), ('3', 'General Science'), ('4', 'Bangladesh and Global Studies'), ('5', 'Religion and Moral Studies'), ('6', 'ICT'), ('7', 'Physics'), ('8', 'Chemistry'), ('9', 'Biology'), ('10', 'Higher Math'), ('11', 'Accounting'), ('12', 'Finance, Banking, and Insurance'), ('13', 'Business Entrepreneurship'), ('14', 'Agricultural Studies'), ('16', 'Statistics'), ('17', 'Business Organization and Management'), ('18', 'Production Management and Marketing'), ('19', 'Economics'), ('20', 'Psychology'), ('21', 'Logic'), ('22', 'Sociology'), ('23', 'Social Work'), ('24', 'Geography'), ('25', 'Studies of Islam'), ('26', 'Home Science')], max_length=150, null=True)),
                ('more_options', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Sports_Section', 'Sports Section'), ('Extra_Curricular_Activities', 'Extra Curricular Activites'), ('Language Learning', 'Language Learning'), ('Computer Learning', 'Computer Learning'), ('Singing_Seciton', 'Singing Section'), ('Dance_Section', 'Dance Section')], max_length=100, null=True)),
                ('experience', models.CharField(choices=[('Null', 'No experience'), ('<0.5', 'Less than 1 Year'), ('1', '1 Year'), ('2', '2 Years'), ('3', '3 Years'), ('4', '4 Years'), ('5', '5 Years'), ('>5', 'More than 5 years')], max_length=100, null=True)),
                ('salary', models.CharField(blank=True, max_length=100)),
                ('days_per_week', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], default='5', max_length=5)),
                ('qualification', models.CharField(choices=[('1', 'PSC or Equivalent'), ('2', 'JSC or Equivalent'), ('3', 'SSC or Equivalent'), ('4', 'HSC or Equivalent'), ('5', 'Bachelor'), ('6', "Master's"), ('7', 'Master of Philosopy')], max_length=20)),
                ('graduated_from', models.CharField(blank=True, max_length=100)),
                ('major_subject', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Busy', 'Busy')], max_length=100)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='session.District')),
                ('division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='session.Division')),
                ('upazilla', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='session.Upazilla')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tuitionprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district', to='session.Division'),
        ),
    ]
