# Generated by Django 3.0.14 on 2022-05-25 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0037_auto_20220524_0054'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('session', '0003_auto_20220517_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='TuitionProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', multiselectfield.db.fields.MultiSelectField(choices=[('Group_Tuition', 'Group Tuition'), ('Private_Tuition', 'Private Tuition')], max_length=100)),
                ('place', multiselectfield.db.fields.MultiSelectField(choices=[('Class_Rooms', 'Class Rooms'), ('Coaching_Center', 'Coaching Center'), ('Home_Visit', 'Home Visit'), ('My_Place', 'My Place'), ('Online', 'Online')], max_length=100)),
                ('approcah', multiselectfield.db.fields.MultiSelectField(choices=[('Online_Help', 'Online Help'), ('Phone_Help', 'Phone Help'), ('Provide_Hand_Notes', 'Provide Hand Notes'), ('Video_Tutorials', 'Video Tutorials')], max_length=100)),
                ('medium', multiselectfield.db.fields.MultiSelectField(choices=[('Bangla_Medium', 'Bangla Medium'), ('English_Medium', 'English Medium'), ('Arabic_Medium', 'Arabic Medium'), ('Sports_Section', 'Sports Section'), ('Singing_Seciton', 'Singing Section'), ('Dance_Section', 'Dance Section'), ('Extra_Curricular_Activities', 'Extra Curricular Activites'), ('Language Learning', 'Language Learning'), ('Computer Learning', 'Computer Learning')], max_length=100)),
                ('salary', models.CharField(max_length=100)),
                ('days_per_week', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Busy', 'Busy')], max_length=100)),
                ('Class_in', models.ManyToManyField(related_name='classes', to='tuition.Class_in')),
                ('Subject', models.ManyToManyField(related_name='subjects', to='tuition.Subject')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='district', to='tuition.District')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tuitionprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
