# Generated by Django 3.0.14 on 2022-07-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0004_auto_20220703_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuitionprofile',
            name='id_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='session/id_certificate/'),
        ),
    ]
