# Generated by Django 3.0.14 on 2022-05-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0037_auto_20220524_0054'),
        ('session', '0004_tuitionprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tuitionprofile',
            old_name='approcah',
            new_name='approach',
        ),
        migrations.RemoveField(
            model_name='tuitionprofile',
            name='Class_in',
        ),
        migrations.RemoveField(
            model_name='tuitionprofile',
            name='Subject',
        ),
        migrations.AddField(
            model_name='tuitionprofile',
            name='class_in',
            field=models.ManyToManyField(related_name='classes', to='tuition.Class_in'),
        ),
        migrations.AddField(
            model_name='tuitionprofile',
            name='subject',
            field=models.ManyToManyField(related_name='subjects', to='tuition.Subject'),
        ),
        migrations.AlterField(
            model_name='tuitionprofile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
