# Generated by Django 3.0.14 on 2022-06-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0006_auto_20220531_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profession',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Student', 'Gurdian/Student'), ('Teacher', 'Teacher')], max_length=50, null=True),
        ),
    ]
