# Generated by Django 3.0.14 on 2022-06-28 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('session', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=17)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=50, null=True)),
                ('student_count', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('More than 4', 'More than 4')], default='1', max_length=50)),
                ('slug', models.CharField(default=models.CharField(max_length=100), max_length=100)),
                ('available', models.BooleanField(default=True)),
                ('category', models.CharField(choices=[('Student', 'Student'), ('Tutor', 'Tutor')], max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('medium', multiselectfield.db.fields.MultiSelectField(choices=[('Arabic_Medium', 'Arabic'), ('Bangla_Medium', 'Bangla'), ('English_Medium', 'English')], max_length=100)),
                ('image', models.ImageField(default='student.png', upload_to='tuition/images/')),
                ('salary', models.FloatField()),
                ('days_per_week', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], default='5', max_length=5)),
                ('details', models.TextField()),
                ('applicants', models.ManyToManyField(related_name='applicant_set', to=settings.AUTH_USER_MODEL)),
                ('class_in', models.ManyToManyField(related_name='class_in_set', to='session.Class_in')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='session.District')),
                ('division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='session.Division')),
                ('likes', models.ManyToManyField(related_name='post_likes', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ManyToManyField(related_name='subject_set', to='session.Subject')),
                ('upazilla', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='session.Upazilla')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('views', models.ManyToManyField(related_name='post_views', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Postfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tuition.Post')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tuition.Comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuition.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
