# Generated by Django 3.0.14 on 2022-06-28 11:11

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='class_in',
        ),
        migrations.RemoveField(
            model_name='post',
            name='subject',
        ),
        migrations.AddField(
            model_name='post',
            name='classes',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('0', 'Pre-Primary'), ('1', 'Class 1'), ('2', 'Class 2'), ('3', 'Class 3'), ('4', 'Class 4'), ('5', 'Class 5'), ('6', 'Class 6'), ('7', 'Class 7'), ('8', 'Class 8'), ('9', 'Class 9'), ('10', 'Class 10'), ('11', 'College Student'), ('12', 'University Student'), ('13', 'Madrasha Student'), ('14', 'Technical Student'), ('15', 'Diploma Student')], max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='subjects',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('0', 'Arabic'), ('1', 'Bangla'), ('3', 'English'), ('2', 'Math'), ('3', 'General Science'), ('4', 'Bangladesh and Global Studies'), ('5', 'Religion and Moral Studies'), ('6', 'ICT'), ('7', 'Physics'), ('8', 'Chemistry'), ('9', 'Biology'), ('10', 'Higher Math'), ('11', 'Accounting'), ('12', 'Finance, Banking, and Insurance'), ('13', 'Business Entrepreneurship'), ('14', 'Agricultural Studies'), ('16', 'Statistics'), ('17', 'Business Organization and Management'), ('18', 'Production Management and Marketing'), ('19', 'Economics'), ('20', 'Psychology'), ('21', 'Logic'), ('22', 'Sociology'), ('23', 'Social Work'), ('24', 'Geography'), ('25', 'Studies of Islam'), ('26', 'Home Science')], max_length=150, null=True),
        ),
    ]
