# Generated by Django 3.0.14 on 2022-06-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_auto_20220629_0100'),
        ('tuition', '0003_post_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='candidate',
            field=models.ManyToManyField(related_name='candidate', to='session.TuitionProfile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male Tutor'), ('Female', 'Female Tutor'), ('Any', 'Any')], max_length=20, null=True),
        ),
    ]
