# Generated by Django 3.0.14 on 2022-07-01 06:25

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0004_auto_20220630_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='starting_from',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='classes',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Pre-Primary', 'Pre-Primary'), ('Class 1', 'Class 1'), ('Class 2', 'Class 2'), ('Class 3', 'Class 3'), ('Class 4', 'Class 4'), ('Class 5', 'Class 5'), ('Class 6', 'Class 6'), ('Class 7', 'Class 7'), ('Class 8', 'Class 8'), ('Class 9', 'Class 9'), ('Class 10', 'Class 10'), ('SSC Candidate', 'SSC Candidate'), ('College Student', 'College Student'), ('HSC Candidate', 'HSC Candidate'), ('University Student', 'University Student'), ('Madrasha Student', 'Madrasha Student'), ('Technical Student', 'Technical Student'), ('Diploma Student', 'Diploma Student'), ('Course Student', 'Course Student')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='subjects',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Arabic', 'Arabic'), ('Bangla', 'Bangla'), ('English', 'English'), ('Math', 'Math'), ('General Science', 'General Science'), ('Bangladesh and Global Studies', 'Bangladesh and Global Studies'), ('Religion and Moral Studies', 'Religion and Moral Studies'), ('ICT', 'ICT'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('Higher Math', 'Higher Math'), ('Accounting', 'Accounting'), ('Finance, Banking, and Insurance', 'Finance, Banking, and Insurance'), ('Business Entrepreneurship', 'Business Entrepreneurship'), ('Agricultural Studies', 'Agricultural Studies'), ('Statistics', 'Statistics'), ('Business Organization and Management', 'Business Organization and Management'), ('Production Management and Marketing', 'Production Management and Marketing'), ('Economics', 'Economics'), ('Psychology', 'Psychology'), ('Logic', 'Logic'), ('Sociology', 'Sociology'), ('Social Work', 'Social Work'), ('Geography', 'Geography'), ('Studies of Islam', 'Studies of Islam'), ('Home Science', 'Home Science'), ('All Subjects', 'All Subjects')], max_length=150, null=True),
        ),
    ]
