# Generated by Django 3.0.14 on 2022-07-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0003_auto_20220701_1225'),
        ('tuition', '0005_auto_20220701_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tutor',
            field=models.ManyToManyField(related_name='tutor', to='session.TuitionProfile'),
        ),
    ]
