# Generated by Django 3.0.14 on 2022-05-03 14:31

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0006_auto_20220502_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='medium',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Bangla', 'Bangla'), ('English', 'English'), ('Hindi', 'Hindi'), ('Urdu', 'Urdu'), ('Arabic', 'Arabic')], default='Bangla', max_length=200),
        ),
    ]
