# Generated by Django 3.0.14 on 2022-07-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0006_post_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='salary',
            field=models.IntegerField(),
        ),
    ]
