# Generated by Django 3.0.14 on 2022-05-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0007_post_medium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='tuition/images'),
        ),
    ]
