# Generated by Django 3.0.14 on 2022-05-06 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0009_auto_20220506_2154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='i',
        ),
    ]
