# Generated by Django 3.0.14 on 2022-05-06 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0010_auto_20220506_2157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='i',
            new_name='image',
        ),
    ]
