# Generated by Django 3.0.14 on 2022-05-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0012_auto_20220506_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='tuition/images/'),
        ),
    ]
