# Generated by Django 3.0.14 on 2022-05-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0013_auto_20220506_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='tuition/images/default.jpeg', upload_to='tuition/images/'),
        ),
    ]
