# Generated by Django 3.0.14 on 2022-05-08 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0017_auto_20220508_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='class_in',
        ),
    ]
