# Generated by Django 3.0.14 on 2022-05-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0018_remove_post_class_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='class_in',
            field=models.ManyToManyField(related_name='class_set', to='tuition.Class_in'),
        ),
    ]
