# Generated by Django 3.0.14 on 2022-05-08 18:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tuition', '0019_post_class_in'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='PostForm',
        ),
    ]
