# Generated by Django 3.0.14 on 2022-05-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0021_auto_20220509_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='class_in',
            field=models.ManyToManyField(related_name='class_set', to='tuition.Class_in'),
        ),
        migrations.AddField(
            model_name='post',
            name='subject',
            field=models.ManyToManyField(related_name='subject_set', to='tuition.Subject'),
        ),
    ]
