# Generated by Django 3.0.14 on 2022-05-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0023_auto_20220510_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Student', 'Student'), ('Tutor', 'Tutor')], max_length=100),
        ),
    ]
