# Generated by Django 3.0.14 on 2022-05-20 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0026_auto_20220517_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tuition/images')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tuition.Post')),
            ],
        ),
    ]
