# Generated by Django 3.0.14 on 2022-05-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0027_postfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multipleimages', models.FileField(blank=True, null=True, upload_to='tuition/gallery/')),
            ],
        ),
        migrations.AlterField(
            model_name='postfile',
            name='image',
            field=models.ImageField(upload_to='tuition/images/'),
        ),
    ]
