# Generated by Django 3.0.14 on 2022-05-22 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0028_auto_20220520_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='PhotoGallery',
        ),
        migrations.AddField(
            model_name='post',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='postfile',
            name='image',
            field=models.ImageField(upload_to='gallery/'),
        ),
    ]
