# Generated by Django 3.0.14 on 2022-05-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0029_auto_20220522_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='district',
            field=models.CharField(default='Dhaka', max_length=100),
        ),
    ]
