# Generated by Django 3.0.14 on 2022-05-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0030_auto_20220522_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
