# Generated by Django 3.0.14 on 2022-05-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0031_auto_20220522_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='district',
        ),
        migrations.AddField(
            model_name='post',
            name='district',
            field=models.ManyToManyField(related_name='district_set', to='tuition.District'),
        ),
    ]
