# Generated by Django 3.0.14 on 2022-05-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0032_auto_20220522_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='district',
        ),
        migrations.AddField(
            model_name='post',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
