# Generated by Django 3.0.14 on 2022-05-23 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0033_auto_20220523_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='tuition/default.png', upload_to='tuition/images/'),
        ),
    ]
