# Generated by Django 3.0.14 on 2022-05-30 18:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tuition', '0037_auto_20220524_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='applicants',
            field=models.ManyToManyField(related_name='applicant_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
